# Generated by Django 4.2 on 2023-08-09 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "production")], default=1
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="NotificationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_channel",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "email"), (2, "sms")], default=1
                    ),
                ),
                ("subject", models.CharField(max_length=300)),
                ("body", models.TextField()),
                ("endpoint", models.CharField(max_length=150)),
                ("created_datetime", models.DateTimeField(auto_now=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="notifications.notification",
                    ),
                ),
            ],
        ),
    ]
