# Generated by Django 4.2 on 2023-08-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ("-created_datetime",)},
        ),
        migrations.AddField(
            model_name="notification",
            name="total_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="notificationitem",
            name="is_successful",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "license expiration")], default=1
            ),
        ),
    ]
